# Tomcat
server:
    port: 8083
    context-path: /wind-file
    connection-timeout: 5000
    tomcat:
        uri-encoding: UTF-8  # character encoding to use for URL decoding
        max-threads: 1000
        min-spare-threads: 30

#Spring 配置
spring:
    profiles: dev # 开发环境配置
    messages:
        encoding: UTF-8
    http:
        encoding:
            charset: UTF-8
            enabled: true
            force: true

#日志记录
logging:
    config: "classpath:Logback.xml"
    #path: d:/log
    file: d:/logs/wind-file

#系统消息通知 配置
system:
    msg:
        addMsg: 增加成功
        editMsg: 修改成功
        removeMsg: 删除成功
    upload:
        file: d:\upload\file #阿姨项目的图片的上传地址
        img: d:\upload\img #阿姨项目的图片的上传地址
    publicPath:  /uwcost/register|/uwcost/active|/uwcost/login|/uwcost/verifyMailAndCode|/uwcost/editpwd|/uwcost/verifyCode|/api/monitoring/** #公共地址
    serverNamePortPath: http://localhost:8083
    #serverNamePortPath: http://58.51.90.231:8083
    #serverNamePortPath: http://file.ivfcn.com




